### ISSUE TITLE
Factor out rxros_tf from rxros

### ISSUE THREAD

**Issue by wasowski** [rosin-project/rxros#8]
See issue #3 . It should be possible to get the core part of rxros be completely independent from tf.

**Comment by gavanderhoorn** [comment]
Some initial work: https://github.com/rosin-project/rxros/compare/master...gavanderhoorn:refactor_tf_support.

**Comment by gavanderhoorn** [comment]
@henrik7264: I've noticed that `observable` is currently a class ([here](https://github.com/rosin-project/rxros/blob/5bb5fb3fab9ab06e846728a44196c57434312b2a/rxros/include/rxros/rxros.h#L200)), but all methods are `static` ([here](https://github.com/rosin-project/rxros/blob/5bb5fb3fab9ab06e846728a44196c57434312b2a/rxros/include/rxros/rxros.h#L222) fi).

Would it be possible to make an `observable` namespace instead of a class? That would make adding to the `rxros` namespace easier (from `rxros_tf` fi).

For now I've created an additional `rxros_tf` namespace to allow the second `observable` class to co-exist with the one in `rxros`.

(note: I've not actually used this yet, so it could be that this is a silly/stupid question/suggestion)

**Comment by gavanderhoorn** [comment]
And just an observation: besides this:

https://github.com/rosin-project/rxros/blob/5bb5fb3fab9ab06e846728a44196c57434312b2a/rxros/include/rxros/rxros.h#L229

`rxros_tf` appears to be independent from `rxros` itself (the TF related code only uses `rxcpp`, `roscpp` and `tf`).

**Comment by henrik7264** [comment]
Hi Gijs

I shall look at it later this evening.

Regards Henrik

**Comment by henrik7264** [comment]
I actually think there is a good chance that the class may be replaced by a namespace. Thinking about it I actually better like this approach.

I shall check it later to night. I am on work now.

**Comment by henrik7264** [comment]
Here is a proposal for how the rxros.h and rxros_tf.h could be made.
[rxros.zip](https://github.com/rosin-project/rxros/files/3563650/rxros.zip)

**Comment by gavanderhoorn** [comment]
@henrik7264: looking at the contents of the zip file it appears the biggest changes are the introduction of the `rxros_tf.h` header and the fact that `observable` is now a `namespace`. Correct?

That all looks OK to me.

Would you want to submit that as a pull request against this repository?

**Comment by henrik7264** [comment]
@gavanderhoorn yes the zip file is a proposed split of the rxros.h into a rxros_tf.h and a rxros.h without tf. The second change is to use a namespace instead of the observable class.
Yes it would be nice to have this as a pull request against this repository.

**Comment by henrik7264** [comment]
@gavanderhoorn could I kindly ask you to make the necessary preparation with respect distributing the files to the appropriate repositories and setup up all the nice ROS workspace magic. I shall be happy to review and merge them later.

**Comment by gavanderhoorn** [comment]
@henrik7264: see #24, which is a continuation of the work I mentioned in https://github.com/rosin-project/rxros/issues/8#issuecomment-526909032 combined with the changes you proposed in your `.zip` in https://github.com/rosin-project/rxros/issues/8#issuecomment-526928704.

If you could review that would be great.
